#pragma once


#define FDE_DEVICE_DESCRIPTOR_OFFSET    0x208   


#define FDE_DEVINFO_OFFSET              0xA0    

#define FDE_DISPATCH_TABLE_OFFSET       0x1C0   

#define CDE_LOWER_DEVICE_OFFSET         0x10    

#define CDE_PARTITION_ZERO_OFFSET       0x18    

#define CDE_DRIVER_EXTENSION_OFFSET     0x20    

#define FDE_SCSI_IDENTITY_OFFSET        0x240   

#define DEVINFO_CLASS_DEVICE_CONTROL_OFFSET  0x20  

#define DISPATCH_TABLE_DEVICE_CONTROL_INDEX  14     

#define STORAGE_DEVICE_DESCRIPTOR_MIN_VERSION  0x24  
#define STORAGE_DEVICE_DESCRIPTOR_MAX_SIZE     4096  

#define SCSI_IDENTITY_POOL_TAG  'sDcS'  

#define BUSTYPE_MAX_VALID       20

